apiVersion: v1
kind: Service
metadata:
  name: b2b-aggregation
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: b2b-aggregation
  type: NodePort
